select = [
  "E", "F", "W", # flake8
  "B",           # flake8-bugbear
  "I",           # isort
  "ARG",         # flake8-unused-arguments
  "C4",          # flake8-comprehensions
  "EM",          # flake8-errmsg
  "ICN",         # flake8-import-conventions
  "ISC",         # flake8-implicit-str-concat
  "G",           # flake8-logging-format
  "PGH",         # pygrep-hooks
  "PIE",         # flake8-pie
  "PL",          # pylint
  "PT",          # flake8-pytest-style
  "RET",         # flake8-return
  "RUF",         # Ruff-specific
  "SIM",         # flake8-simplify
  "UP",          # pyupgrade
  "YTT",         # flake8-2020
  "EXE",         # flake8-executable
  "NPY",         # NumPy specific rules
  "PD",          # pandas-vet
]
extend-ignore = [
  "PLR",    # Design related pylint codes
  "E501",   # Line too long
  "NPY002", # Replace legacy random
  "PD008",  # False positive with Jax
]
target-version = "py38"

[per-file-ignores]
"*.ipynb" = [
  "B018",    # Useless expression
  "F811",    # Redefinition of unused
  "B015",    # Pointless comparison
  "E402",    # Module level import not at top of file
  "E703",    # Notebooks often have "pointless" semicolons
  "I001",    # Hard to get right with IPython
  "F704",    # await outside function (allowed in IPython)
  "PLE1142", # await outside async function (allowed in IPython)
  "PD901",   # df is a bad variable name
]
"check.py" = [
  "F401", # This files does this
]
"02_temperatures.ipynb" = [
  "F401", # Unused import is used in %%timeit
  "F821", # Can't look inside magic (yet)
]
"03_mcmc.ipynb" = ["F821"]
"08_pandas_covid.ipynb" = ["F821"]
