name: performance-minicourse
channels:
  - conda-forge
dependencies:
  - python >=3.7
  - numpy >=1.18
  - matplotlib >=3
  - pandas >=1
  - scipy >=1.2
  - jupyterlab >=2
  - plumbum >=1.6.9
  - numba >=0.49
  - numexpr >=2.7
  - tensorflow >=1.13
  - dask
  - distributed
  - nb_conda_kernels
  - line_profiler
  - ipywidgets
  - nodejs
  - ipympl
  - python-graphviz
